### ISSUE TITLE
Does it possible to check if user has permission to access INTERNET and warn if not?

### ISSUE THREAD

**Issue by DASAR** [square/picasso#1062]
There is a lot of topics on stackoverflow with same mistake. Frequently users just forget to add this permission to their app manifest file:
```xml
<uses-permission android:name="android.permission.INTERNET" />
```
And then they cannot easily understand why their requests is not working (errored). Does it possible to add check inside load() API for example and log something helpful in case if request failed? My point is to help users easily find this mistake.

**Comment by JakeWharton** [comment]
Picasso can load from a bunch of different locations, the network being only one. Moreover, we used to do this check and actually found that certain ROMs would crash on the internet check (ugh). While I think this occasionally trips people up, I don't think it's as widespread as we think and the fix is a "duh" moment than anything more complex.

See also #596 #603 #748 #1027

**Comment by DASAR** [comment]
Thanks for the explanation.
