### ISSUE TITLE
HI，This's a good idea？

### ISSUE THREAD

**Issue by ikkyu0319** [square/picasso#1077]
/**
         * Start an image request using the specified path. This is a convenience method for calling
         * {@link #load(Uri)}.
         * <p>
         * This path may be a remote URL, file resource (prefixed with {@code file:}), content resource
         * (prefixed with {@code content:}), or android resource (prefixed with {@code
         * android.resource:}.
         * <p>
         * Passing {@code null} as a {@code path} will not trigger any request but will set a
         * placeholder, if one is specified.
         * @see #load(Uri)
         * @see #load(File)
         * @see #load(int)
         * @throws IllegalArgumentException if {@code path} is empty or blank string.
         */
        public RequestCreator load(String path) {

          if (path == null) {
            return new RequestCreator(this, null, 0);
          }
          if (path.trim().length() == 0) {
            throw new IllegalArgumentException("Path must not be empty.");
          }
           return load(Uri.parse(path));
        }

         
This my code

         Picasso.with(this).load(mSimplePlan.getCover()).placeholder(R.drawable.ic_default).resize(width, height).centerCrop().into(ivPlanPhoto);

  when "mSimplePlan.getCover()== null"    is OK? 
     but mSimplePlan.getCover().trim().length() ==0 
        throw new IllegalArgumentException("Path must not be empty.");

        public RequestCreator load(String path) {

          if (path == null||(path.trim().length() == 0) {
            return new RequestCreator(this, null, 0);
          }
           return load(Uri.parse(path));
        }

Why Not ?????

**Comment by ikkyu0319** [comment]
@JakeWharton  Hello ,Look Here ~~~

**Comment by JakeWharton** [comment]
This is working as intended. An empty string is not a valid URL. If you want to allow an empty string (or, as another example, a blank string `"  "`) then you should canonicalize it to `null` before calling into Picasso.

We are unforgiving here because an empty string usually indicates a larger problem with data representation and we don't want to hide the problem. `null` is an explicit value and a valid URL is an explicit value and those are the only two things Picasso accepts.
