### ISSUE TITLE
Wrong image getting loaded in adapter

### ISSUE THREAD

**Issue by dhrushilbadani** [square/picasso#1111]
I have an adapter with a getView that displays an image (setting it as the background for the view using a Target) and the title of the image together. Now, the images get interchanged on scrolling for some reason. As in, if image1 is for text1 and image2 is for text2, it gets swapped. Any idea on how I can fix this? Here's the code for the getView method of my adapter:

{
public View getView(final int position, View convertView, ViewGroup parent) {
        if (convertView == null) {
            LayoutInflater inflater = (LayoutInflater) mContext
                    .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
            postSingle = new View(mContext);
            postSingle = inflater.inflate(R.layout.post_single, null);
        } else {
            postSingle = convertView;
        }
            ImageView postImage = (ImageView) postSingle.findViewById(R.id.postImage);
            Picasso.with(mContext).cancelRequest(postImage);
            TextView titleText = (TextView) postSingle.findViewById(R.id.titleText);
            TextView dateText = (TextView) postSingle.findViewById(R.id.dateText);
            TextView usernameText = (TextView) postSingle.findViewById(R.id.usernameText);
            TextView likesText = (TextView) postSingle.findViewById(R.id.likesText);
            TextView dislikesText = (TextView) postSingle.findViewById(R.id.dislikesText);
            TextView commentsText = (TextView) postSingle.findViewById(R.id.commentsText);
            String useURL = "";
            //Log.d("useURL", useURL);
            useURL = "http://www.somewebsite.com/" + mPic_urlList.get(position);
            if (useURL != "") {
                //Picasso.with(mContext).load(useURL.replaceAll(" ", "%20")).into(postImage);
                Picasso.with(mContext).load(useURL).resize(postSingle.getWidth(), 280).into(new Target() {

                    @Override
                    public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
                        postSingle.setBackground(new BitmapDrawable(mContext.getResources(), bitmap));

                    }

                    @Override
                    public void onBitmapFailed(final Drawable errorDrawable) {
                        Log.d("TAG", "FAILED");
                    }

                    @Override
                    public void onPrepareLoad(final Drawable placeHolderDrawable) {
                        Log.d("TAG", "Prepare Load");
                    }
                });
            }
}

**Comment by JakeWharton** [comment]
In the future, StackOverflow and the 'picasso' tag is the right place for usage questions. This is not a support forum, just a place for tracking bugs and feature requests.

```java
postSingle = new View(mContext);
postSingle = inflater.inflate(R.layout.post_single, null);
```
The first line is meaningless as its content is overridden by what's returned from the inflater.

```java
if (useURL != "") {
```
String comparisons should be done with `equals`. This comparison is also always true since you set the `useURL` variable directly above the `if` statement to always be non-empty.

```java
Picasso.with(mContext).cancelRequest(postImage);
```
You are canceling old requests with `postImage` but below you load an image with a Target. This line will never do anything.

```java
Picasso.with(mContext).load(useURL).resize(postSingle.getWidth(), 280).into(new Target() {
```
Calling `.into(new Target() {` is **always** wrong because it means that nothing has a strong reference to the `Target`. Since Picasso keeps a weak reference to anything you pass it, the `Target` will be garbage collected immediately. This means that unless you images are already in memory they will never show up. Try creating the `Target` and setting it as the tag of `postImage` so that something keeps a reference to it. And remember, if you are canceling a request you need to use this `Target` instance and _not_ just `postImage`.
