### ISSUE TITLE
Picasso not loading from disc

### ISSUE THREAD

**Issue by alfco333** [square/picasso#1170]
Hello everyone, I am having a problem loading images from discache. The thing is when I download  a couple houndred of images using the fetch, once I reload my app every image is loaded from the disc again, but once I fetch around 800 or more, when I reload every image appears to be loaded from the network; I am implementing Okhttp and the cache file that  is using seems to be full of images, but no one is loaded from it. I have been researching these last days but I haven't found any solution to this problem. The last piece  code I came up with is this: 

      sInstance.load(url).resize(width,height).networkPolicy(NetworkPolicy.OFFLINE).fetch(new          Callback()     {
            @Override
            public void onSuccess() {
                if(listener!=null) {
                    listener.onLoadingComplete(url, null, null);
                }
            }

            @Override
            public void onError() {
                sInstance.load(url)
                        .config(Bitmap.Config.RGB_565)
                        .resize(width, height)
                        .fetch(createCallbackNoDisplay(url, listener));
            }
        });

I found this solution to force picasso to read the disc cache first, but it's not working; any help is appreciated.
Note: this is the configuration that is used to init Picasso

       public static Picasso getImageLoaderConfig(Context context, int memoryCacheSize, File cacheDir, long diskCacheSize,
                                               SSLSocketFactory sslSocketFactory, HostnameVerifier hostnameVerifier) {
        sDiskCache = cacheDir;
        sMemoryCache = new LruCache(memoryCacheSize);
        OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.setHostnameVerifier(hostnameVerifier);
        okHttpClient.setSslSocketFactory(sslSocketFactory);
        okHttpClient.setCache(new Cache(cacheDir, diskCacheSize));
      
        return new Picasso.Builder(context)
                .memoryCache(sMemoryCache)
                .loggingEnabled(false) // true only for debug purposes
                .indicatorsEnabled(BuildConfig.DEBUG) // true only for debug purposes, show from where the image is being loaded
                .downloader(new OkHttpDownloader(okHttpClient))
                .build();
    }

**Comment by JakeWharton** [comment]
Picasso has no control over the disk cache so there is nothing in the library that can really be done to affect whether it uses the disk cache or not. It's entirely encapsulated inside the HTTP client.

That said,

> but once I fetch around 800 or more

it's an LRU cache, so once you exceed its size the oldest images will be removed. If you end up loading those 800 images in order again, the first ones won't be in the cache because they were removed, and the act of loading them will cause them to be cached and remove the ones further down the list thus causing them not to be loaded from the cache either.

You either need to increase the size of your disk cache, reduce the number of pre-cached images, or store the cached images yourself in your own local cache where you can ensure they all will be retained (or some combination of all three of those).
