### ISSUE TITLE
Resample image after zooming in

### ISSUE THREAD

**Issue by luccascorrea** [square/picasso#1193]
Hi,

I am using Picasso along with TouchImageView (https://github.com/MikeOrtiz/TouchImageView) in order to provide pinch to zoom functionality. The issue I see is that, even though my original image has a high resolution, when loading it with Picasso, it gets downsampled and so when I zoom in, the quality deteriorates.

The TouchImageView class has a callback that lets me know when the user zoomed in and at that point I can also know the new size of the image. I tried using Picasso's resize method in order to recalculate the bitmap size based on the new size of the image without success. 

Is there a way to tell picasso to reload the image with a higher resolution after it is zoomed in?

Thanks in advance! Any help will be greatly appreciated!

**Comment by Hofferic** [comment]
Can you show the code you used to try this?
The Picasso memory cache uses the parameters as part if the cache key so a new request with different resize parameters should always return the correct size and relatively high quality regardless of the cache.

So if you get the current bitmap from your view and set it as the placeholder of your request with the correct new resize parameters it should even fade nicely (as long as you only do so on completion of the resize or in steps)

**Comment by luccascorrea** [comment]
The code I am using is the following:

    private void initUI(View rootView){
        this.mediaItem = getArguments().getParcelable("mediaItem");
        final String url = mediaItem.getFullUrl();
        img = (TouchImageView) rootView.findViewById(R.id.imgDisplay);
        img.setOnTouchImageViewListener(this);
        final View pb = rootView.findViewById(R.id.pbImgDisplay);
        Picasso picasso = MediaUtils.getPicasso();
        picasso.with(this.getActivity())
                .load(mediaItem.getThumbnailUrl())
                .placeholder(R.drawable.ic_image_placeholder)
                .fit()
                .centerInside()
                .into(img, new Callback() {
                    @Override
                    public void onSuccess() {
                        pb.setVisibility(View.GONE);
                    }

                    @Override
                    public void onError() {
                        pb.setVisibility(View.GONE);
                    }
                });

    }

    @Override
    public void onMove() {
        Picasso picasso = MediaUtils.getPicasso();
        picasso.with(this.getActivity())
                .load(mediaItem.getThumbnailUrl())
                .placeholder(img.getDrawable())
                .resize(img.getImageWidth(), img.getImageHeight())
                .into(img);
    }

The method "onMove" is called everytime the user zooms in or out. What I noticed is that calling "resize" does not improve the image quality. The particular image I am testing with is 1500 x 971 px. Even when I call `resize(1500, 971)`, it is not shown in its full size and it looks blurry when zooming in.

Thanks for the help!

**Comment by Hofferic** [comment]
To me this all looks correct.
Have you tried putting a log call in onMove to verify it gets called as expected and img.getImageWidth() and img.getImageHeight() return the expected values instead of, for example, the size of the current bitmap? Also make sure onMove is not called after every touch event or, in case it is, make sure your code only runs after the user stops moving or the last zoom operation is done and consider adding a cache policy to skip the memory cache for zoom intermediates to avoid calling on picasso tens of times a second or overloading the cache. Doing so may cause problems (unnecessary managing overhead being the best case).

Also try adding a callback to your onMove picasso call and log the result (success, failure and possibly result data) to verify that picasso is able to load the image as specified and the resulting bitmap matches the dimensions you specified in your load call.

**Comment by luccascorrea** [comment]
It worked! 

As you suggested, I created a callback that is only called after the user stops moving. I also realized that I was using the wrong url to load the image, I was loading the thumbnail instead of the full image (how stupid of me) and that is why resizing didn't make a difference.

Thanks a lot for your help!
