### ISSUE TITLE
Image loading on Android 4.1.2 is very slow

### ISSUE THREAD

**Issue by oizo** [square/picasso#1202]
It seems Picasso 2.5.2 has a bug while loading images on Android 4.1.2/4.1.1. The load time for loading three images from web, is around 10-20 seconds, while trying to load the same three images with Android Universal Image Loader takes around 1-3 seconds.

I've come across the problems on a Samsung Galaxy SIII Mini (GT-I8190N) running Android 4.1.2. And i've gotten a single complaint about load times on a LG Optimus G (LG-E975), though the LG isn't verified as I haven't got access to such a device.

I've easily been able to reproduce the problem in this demo app on the GT-I8190N. The bug also seems to be reproducible (with even worse load times, around 90 seconds) on an Android Emulator running Android 4.1.1 (SDK 16), available via the AVD Manager.

I've created a small project demonstrating the problem here: https://github.com/oizo/PicassoProblem

**Comment by ming13** [comment]
Have no idea if the issue is still relevant, but have you tried using Picasso in combination with OkHttp? Just include OkHttp 2 as a dependency (OkHttp 3 is not supported by the latest Maven Central release yet). [Picasso will build the downloader for you automagically](https://github.com/square/picasso/blob/ebce0a70c446b32c6fd7a6f0c5bde595925ecca1/picasso/src/main/java/com/squareup/picasso/Utils.java#L248-L262).

**Comment by oizo** [comment]
Yes, it's still relevant :-) It seems that using OkHttp does the trick, as you described, thanks a lot!

```
```
Just include `compile 'com.squareup.okhttp:okhttp:2.7.5'` to `build.gradle` dependencies
