### ISSUE TITLE
Ability to write local images to cache

### ISSUE THREAD

**Issue by toker** [square/picasso#1216]
Hi everyone!
Here is what a want to do.
I have an image that I'm going to upload to server. After upload I have an url of my image. Before upload have started I add an image to recycleview, the image itself is stored locally at that moment. I'm looking for a way to put my image to picasso cache (disk and memory) with key depending on gotten url so it wouldn't be necessary to download it from network. Looks like good idea, cause I already have an image locally, doesn't it?
Firstly I looked through all issues trying to find the solution for my problem. Here they are:
https://github.com/square/picasso/issues/1121
https://github.com/square/picasso/issues/1147
https://github.com/square/picasso/issues/759

but still can't managed to find an answer or an advice ;(

So, what do you think?

**Comment by jonan** [comment]
This is not the right place to ask questions, it should only be used to report real issues.

Stack Overflow is a much better place to look for help.

**Comment by JakeWharton** [comment]
Picasso does not control or even know about the disk cache, and there's no APIs to write into a cache locally, particularly because there's a lot of information that goes into caching at the HTTP client level.

The way that we accomplish this is by using a `stableKey` in our requests which allows you to point to a local file while the image is uploading and then switch to a URL without invalidating the memory cache. This will cause a memory cache miss to download the image again, however, but that's outside our control and really isn't that bad.

**Comment by JakeWharton** [comment]
And since this isn't a bug or a feature request that we can accommodate (Picasso knows nothing about the disk cache as I said), it falls under general usage for which StackOverlow is much more appropriate. There's many more users there that can see and engage on questions about approaches to solve problems like this.

**Comment by toker** [comment]
Ok, I'll try the approach with `stableKey`. Sorry about such question here
