### ISSUE TITLE
Picasso crashed java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by sleith** [square/picasso#1237]
Hi,
My app previously able to run the app using picasso with no problem. But recently not sure what changed (i don't think something changed on gradle), the app crashed when using picasso.

The error is:
java.lang.NoClassDefFoundError: com.squareup.picasso.Picasso$1 at com.squareup.picasso.Picasso.<clinit>(Picasso.java:109)

And some warnings before crashed:
Could not find class 'com.squareup.picasso.Picasso$1', referenced from method com.squareup.picasso.Picasso.<clinit>
unable to resolve new-instance 9596 (Lcom/squareup/picasso/Picasso$1;) in Lcom/squareup/picasso/Picasso;
unable to find class referenced in signature (Lcom/squareup/picasso/Dispatcher;)
unable to find class referenced in signature (Lcom/squareup/picasso/Cache;)
unable to find class referenced in signature (Lcom/squareup/picasso/Stats;)
Could not find class 'com.squareup.picasso.ResourceRequestHandler', referenced from method com.squareup.picasso.Picasso.<init>

My gradle is:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.crittercism:crittercism-android-agent:5.4.0'
    compile 'com.braintreepayments.api:braintree-api:1.7.5'
    compile 'com.google.android.gms:play-services:8.3.0'

}

Multidex is enabled.
Please help >.< 
Thanks

**Comment by JakeWharton** [comment]
This is going to be caused by the use of ProGuard or multidex (or both). As a user of neither I am ill-equipped to provide a recommendation except to say that StackOverflow is a much better place for these types of questions (you can use the 'picasso' tag). There are more people there who are answering question and it serves as a better archive for future searches of similar problems than GitHub issues. Feel free to link to your question here if you post one.
