### ISSUE TITLE
Simplified Target?

### ISSUE THREAD

**Issue by shaunkawano** [square/picasso#1274]
Hi square,

Thanks for open sourcing such an useful library and making our lives easier!

I have a question with regard to [Target interface](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/Target.java); right now, we must override all three methods of this Target interface. Is there any reason or purpose for it?

I've come up with an idea to add a simple abstract class that implements `Target` so that those who use this library can choose to override only certain methods that they use, which maybe looks something like this: 

```java
public abstract class SimpleTarget implements Target {
  @Override
  public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
    // override if necessary
  }

  @Override
  public void onBitmapFailed(Drawable errorDrawable) {
    // override if necessary
  }

  @Override
  public void onPrepareLoad(Drawable placeHolderDrawable) {
    // override if necessary
  }
}
```

I know you guys may have thought of it already and decided not to do so for some reason, so I've decided to write it on issue first. Thanks.

(Sorry if you guys have already provided us this sort of functionality and I've missed that..)

**Comment by NightlyNexus** [comment]
By the way, remember to implement `equals` and `hashCode` on `Target` for Picasso to know to cancel equal previous requests.

**Comment by JakeWharton** [comment]
Right. `Target` needs to have correct `equals` and `hashCode` semantics in order to work, as documented.

Usually `Target` is implemented on something that is usually a view. Since views have a shared base class, an abstract version with empty implementations won't help here since it cannot be used.

You **never** want to call `.into(new SimpleTarget() { ... });` (or `.into(new Target() { ... }`) either since the instances are weakly held which will cause it to immediately be garbage collected and your app to misbehave.

It's because of these two reasons that we don't offer anything like you suggest.

**Comment by shaunkawano** [comment]
Thank you both @NightlyNexus and @JakeWharton. I will make a fresh start.
