### ISSUE TITLE
How to fetch image from network async(basing NIO)?

### ISSUE THREAD

**Issue by likebean** [square/picasso#1290]
Picasso current fetch image from network in background thread to achieve async,But I want to use NIO http(apache async http client) to download image to prevent background threads exhaust.
But when I want to extends Downloader,I find the method is sync(Response load(Uri uri, int networkPolicy)). can add async support(like load(Uri,Callback)) in Downloader?

**Comment by JakeWharton** [comment]
Bytes are streamed from the socket directly to `BitmapFactory` so that when the last byte arrives the `Bitmap` can (almost) immediately be returned. Since `BitmapFactory` has no way to received bytes from an asynchronous channel, switching to NIO would actually require buffering the bytes of every download before passing as a single `byte[]` to `BitmapFactory`. This would slow down image loading since the decoding work could no longer be amortized over the much slower speed of pulling bytes off the socket. The blocking threading model is actually an optimization that makes images appear in the UI faster, and as such we have no plans to support any type of asynchronous loading.

**Comment by likebean** [comment]
Our  motivation using NIO to load image is prevent threads exhaust,I think this is fatal ,and We  can be sustainable to slightly slow of bitmap decoding.

**Comment by JakeWharton** [comment]
The number of threads in use is fixed, so 1000 image requests isn't going to exhaust any resources.

**Comment by likebean** [comment]
If fixed threads exhaust,follow-up image loading will block till preceding loading timeout,I think this experience is bad.

**Comment by JakeWharton** [comment]
That is a goal, too many concurrent requests slow down every request more than if they queue. We choose to queue and limit concurrent requests and there's no reason to use async I/O in that case.

**Comment by likebean** [comment]
But use NIO can ensure follow-up image loading not be blocked by preceding blocked loading,this can not archieve by sync and queue.

**Comment by JakeWharton** [comment]
That is false. Multiple threads loading ensure that does not happen. If all
are blocked waiting on the network, NIO isn't going to solve anything to
make bytes over a flaky, slow, mobile network flow more quickly.

**Comment by likebean** [comment]
Maybe not network issue,maybe some image sites slow and some sites quickly.We not want slow site image loading block image loading from quick site.

**Comment by JakeWharton** [comment]
That still doesn't address the fact that using NIO would slow down every
image load by a non-trivial amount and increase memory pressure on the app
by a non-trivial amount due to having to buffer the entire image
(potentially multi-megabyte) image into memory. Not to mention this
eliminates our ability to resize the image down while streaming the bytes
to BitmapFactory by leveraging the inSampleSize scale factor.

The one hypothetical advantage to NIO does not outweigh the loss of all
these higher-leverage features.
