### ISSUE TITLE
2.6.0 release

### ISSUE THREAD

**Issue by ming13** [square/picasso#1314]
It would be great to have 2.6.0 available at Central. Especially for OkHttp 3 goodies. Yep, I’m aware of `JakeWharton/picasso2-okhttp3-downloader`, but still it would be nice. There are no new things in `master` for about a month, so I thought there are no breaking changes or WIP at the moment.

**Comment by JakeWharton** [comment]
We will make a release when someone finds the time to finish the version. At present no one works on Picasso so it's hard to find the time.

**Comment by jhansche** [comment]
@JakeWharton Another recent commit (somewhere between 2016-02-19 and 2016-03-22) seems to have broken the 2.6.0-SNAPSHOT.  We were relying on the snapshot in order to get the fix from #626 (which was closed by the merge of #1280).

I mentioned in my comment on #1280 that we are uncomfortable using a SNAPSHOT version -- and that finally came to bite us, as I knew it would.  For now, we have been able to go back to the known-working SNAPSHOT that had been used previously, using the syntax mentioned in #1324 to select picasso-2.6.0-20160219.155404-2.

You stated in #1314 that no one is working on Picasso.  If no one's working on it, is there even a point in maintaining your "we have to wait until everything is done for this version before we release it" stance?

What's left in the roadmap for a 2.6.0 release? I'm sure there are others who would be willing to push it along, at least to get to a point where we don't need to reference a SNAPSHOT version.

**Comment by AllenVork** [comment]
com.squareup.picasso:picasso:2.6.0-SNAPSHOT is invalid.

**Comment by eygraber** [comment]
We're closing in on 2 years since the last release. Has no one had 30 minutes to deploy? Send me the keys. I'll do it.

**Comment by mhousser** [comment]
@eygraber yeah we're actively looking at Facebook's Fresco library now. Picasso is certainly looking abandoned over the past couple years (and we've been using it in multiple projects for well beyond 2 years). Sad to see. Fresco has huge momentum behind it, and the backing of a giant like FB. Gonna be a big migration project though.

**Comment by mhousser** [comment]
@eygraber https://github.com/facebook/fresco - last commit not even 2 hours ago.

**Comment by JakeWharton** [comment]
Use Glide not Fresco.

**Comment by JakeWharton** [comment]
Btw releasing takes 2 minutes, not 30, and has never been the blocking factor.

**Comment by eygraber** [comment]
@mhousser @JakeWharton I've been using Glide for a while, but I still have some legacy projects that I don't want to switch over. Besides, it would be nice for the user base to have a release that has so many crucial fixes in it.

**Comment by JakeWharton** [comment]
There will be a release eventually. Picasso works great as-is for us so
it's hard to justify time working on it. Plus image loading is literally
the worst and the bug reports are low quality and usually user error which
only adds to the avoidance.

**Comment by eygraber** [comment]
I hear that

**Comment by sriramtej** [comment]
@JakeWharton  even if i use Glide instead of Picassio in some devices the images from camera is not loading especially in samsung/lenovo mobile devices
