### ISSUE TITLE
Hello, Picasso.load(String path) Crashed when path is a Empty String " "

### ISSUE THREAD

**Issue by jaycee88** [square/picasso#1326]
Can modify like this:

public RequestCreator load(String path) {
    //if (path == null) {
    //  return new RequestCreator(this, null, 0);
    //}
    if (TextUtils.isEmpty(path)) {
      return new RequestCreator(this, null, 0);
    }
    if (path.trim().length() == 0) {
      throw new IllegalArgumentException("Path must not be empty.");
    }
    return load(Uri.parse(path));
  }

**Comment by JakeWharton** [comment]
An empty string is intentionally erroneous input. If you want to coerce an empty string to be equivalent to `null` then you should do that in your application code before calling Picasso.

**Comment by Mobbit** [comment]
I ran into the same problem. It is not clear to me why `null` and an empty string are handled differently. We handle this in the application code now, but I think it would be better to handle an empty sting like `null`. It cannot imagine a situation where a runtime exception is better than ignoring the empty value and loading the placeholder.

If the behaviour should stay the same it would be great to communicate by adding a `throws` declaration to the methods.

**Comment by Tri125** [comment]
Sorry to comment on an old issue but I ran into the same problem. I'm retrieving URL from an API, those URL are required according to my specs and so they will be unmarshalled into an empty string.

Some of the data doesn't have an URL and since this is an invalid URI, I fully expected Picasso to use the Resource defined with RequestCreator.Error() but instead it throws exceptions.

Giving a null string for the URI won't throw an exception but it will never timeout, it will use the placeholder resource and it will never swap to the error resource.

**Comment by JakeWharton** [comment]
null isn't an error, so that is the behavior we expect, yes.

**Comment by Tri125** [comment]
Ok. How would I go about triggering an error to get the error image if I have an invalid URI?

In my use case I receive some URI from an API, the URI could be null, empty, malformed, or point to an dead link. All of those cases are erroneous. My placeholder is an animated spinner so when it tries to download from a valid URI we see that animation. 

However, if given a bad URI I want to fallback to an error image.

**Comment by JakeWharton** [comment]
In all cases but empty the error image will be shown because the URL could
not be fetched. If you want that behavior on empty, check for it yourself
and set the error image directly.
