### ISSUE TITLE
NoSuchFieldError when using NetworkPolicy.OFFLINE

### ISSUE THREAD

**Issue by JonasPrap** [square/picasso#1331]
picasso.load(baseServerUrl + entity.getIcon()).networkPolicy(NetworkPolicy.OFFLINE).get();

Causes:

```
java.lang.NoSuchFieldError: No static field FORCE_CACHE of type Lcom/squareup/okhttp/CacheControl; in class Lcom/squareup/okhttp/CacheControl; or its superclasses (declaration of 'com.squareup.okhttp.CacheControl' appears in /data/app/com.xxx.xxx-1/base.apk:classes2.dex)
        at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:99)
        at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
        at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
        at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
```

Version 2.5.2. I am not using OkHttp client in project (stuck with Volley). Android 5.0.2

**Comment by JakeWharton** [comment]
Something is putting OkHttp on the classpath and probably a very old version of it.

Check `./gradlew :app:dependencies` (replace `app` with whatever your module name is)

**Comment by JonasPrap** [comment]
+--- com.google.maps:google-maps-services:0.1.11
|    +--- com.squareup.okhttp:okhttp:2.0.0
|    |    \--- com.squareup.okio:okio:1.0.0

What would be your suggestion to do in this case? Is it possible to make Picasso ignore that this dependency is added?
Thanks!

**Comment by JakeWharton** [comment]
You can either:
* Make Picasso ignore it by specifying `.downloader(new UrlDownloader())` in a `Picasso.Builder` and then calling `Picasso.setSingletonInstance` with the built `Picasso` instance from the builder.
* Add a dependency on `com.squareup.okhttp:okhttp:2.7.5` so that the latest 2.x OkHttp is used instead of that super super old one.

I would recommend the latter. You're already bundling OkHttp in your app because of that transitive dependency, so why not bundle the latest 2.x version and let Picasso use it over HttpURLConnection.

**Comment by JonasPrap** [comment]
Thanks again!
