### ISSUE TITLE
More consistent null input checks

### ISSUE THREAD

**Issue by mmallozzi** [square/picasso#1384]
Some methods accept null when it's a clear programming error to do so, and they fail silently rather than alert the developer that they're doing something wrong. Many of these methods correspond to other methods (e.g. inverse methods with the same input) that do perform null checks, so making the null checks consistent across all related methods would be ideal. There are other methods that fail on null input when their corresponding methods do just fine with a null input, often falling back to some reasonable default behavior (like showing a placeholder image).

- `Picasso.cancelRequest`: `ImageView`, `Target`, and `RemoteViews` variants. Corresponding methods `RequestCreator.into` all perform null checks, and providing null here is a programming error, so I believe null checks should throw on all these methods.
- `Picasso.cancelTag`, `pauseTag`, `resumeTag`: corresponding method `RequestCreator.tag` performs a null check, and a null tag doesn't make sense, so I believe null checks should throw on all these methods.
- `Picasso.invalidate`: `Uri`, `String`, and `File` variants. Corresponding methods `Picasso.load` all allow null, though the `String` variant fails on a blank/empty input. I'd argue that the `String` variant is commonly used with input coming from an external source like a backend server and therefore should be more permissive - null/empty/blank strings all seem reasonable, especially since there's such a clear and easy fallback to show the placeholder image. `Uri` and `File` objects are both created on the client side so it seems reasonable to reject null in those cases and allow those with invalid paths internally to proceed to the usual fallback placeholder/error behavior. Whatever is decided for `load` should be duplicated in the corresponding `invalidate` method. I believe that the `String` versions should allow null/empty/blank, while the `Uri` and `File` versions should throw on null.

**Comment by JakeWharton** [comment]
> `Picasso.cancelRequest`... null checks should throw on all these methods.

Agree.

> `Picasso.cancelTag`... null checks should throw on all these methods.

Agree

> I'd argue that the String variant is commonly used with input coming from an external source like a backend server and therefore should be more permissive - null/empty/blank strings all seem reasonable

`null` is a very explicit thing. It is the absence of a value and thus we treat it as such in order to make calling into Picasso more convenient.

Take Picasso without `null` handling:
```java
if (url = null) {
  Picasso.with(context).load(url).into(imageView);
} else {
  Picasso.cancelRequest(imageView);
}
```
vs. with it:
```java
Picasso.with(context).load(url).into(imageView);
```

Empty and/or blank strings are a clear data problem, and we don't want to hide data modeling problems for they often are symptomatic of a larger problem caused elsewhere. We explicitly reject them because they are common, but otherwise you would (presumably) get a crash from `Uri.parse`.

We recommend people coerce empty or blank strings to `null` in their app's model layer because it makes explicit the intent of behavior. We also recommend you scold your server engineers for providing such malformed data! We personally let the app crash, and I haven't yet seen an argument that's compelling enough to change such behavior.

**Comment by JakeWharton** [comment]
I'll happily accept a PR for the null checks, otherwise I'll get around to them before 2.6.0 is released.

**Comment by mmallozzi** [comment]
Makes sense - thanks for your perspective!

**Comment by mmallozz** [comment]
It looks like the three tag-related methods still need updating - the attached diff covered cancelRequest nicely.

Also, what do you think of the part about making invalidate at least consistent with load, so that it allows nulls the same way? That way the same variable can be used in a setup-teardown approach with load-invalidate, without special null checks just for the invalidate case.

**Comment by JakeWharton** [comment]
That's fine
