### ISSUE TITLE
Picasso 2.5.2. don't support drawable content providers

### ISSUE THREAD

**Issue by jackesaenz** [square/picasso#1388]
Hi,

According to features Picasso support drawable (RESOURCE LOADING: Resources, assets, files, content providers are all supported as image sources), but don't work.

In my app when using load with drawable, 

Picasso.with(context)
                        .load(R.drawable.imagen)
                        .into(imgViewFoto);

Picasso show me this error:
 
--- SkImageDecoder::Factory returned null

But if adding the placeholder this error dissapear.

 Picasso.with(context)
                        .load(R.drawable.imagen)
                        .placeholder(R.drawable.imagen)
                        .into(imageViewFoto)

**Comment by JakeWharton** [comment]
For placeholder we call `setImageResource` but when loading a drawable we call `BitmapFactory.decodeResource`. The problem is that Android cannot decode the resource and really has nothing to do with Picasso (nor can we do anything to avoid the problem). Try re-encoding the image in a different format, and you can test that it decodes properly with the `BitmapFactory.decodeResource` call.
