### ISSUE TITLE
break points not working in the override method transform when you implement a custom transformation

### ISSUE THREAD

**Issue by frankrod** [square/picasso#1392]
I want to debug a transformation because isn't working at all and if I put break points within the transform method it never calls the break points. Break point is working in the key method though.

**Comment by JakeWharton** [comment]
The transform is only invoke when needed, and in this case it sounds like we had the cached Bitmap and didn't need to invoke it. The reason a breakpoint in key works is because we call that method to assemble the cache key.

Either use `memoryPolicy(NO_CACHE)`, remove the cache, or set the breakpoint on the first time that transform is loaded to ensure it stops inside your transform.
