### ISSUE TITLE
How to keep reloading image until it's available? (Amazon S3)

### ISSUE THREAD

**Issue by elburro1887** [square/picasso#1458]
My scenario is like follows:

- User uploads pic from my app, which is then sent to Amazon S3
- After the upload, the app instantly tries to load the pic via Picasso

Amazon S3 has a small latency period between when the upload completes and the image being available. If Picasso is loading the image in that small time period, it will receive a 403 and never retry. (S3 returns 403 instead of 404 when a resource is not available).

Is there a way to force a retry?

Thanks!

**Comment by JakeWharton** [comment]
There is no way to tell Picasso to retry (beyond the retries it automatically does for network errors). Since this is an application-level logic that you want, I think it makes sense to implement it in your application, not Picasso. You can do this by wrapping Picasso's API into your own image loader API which supports the ability to do these retries by just re-requesting the same URL and monitoring the result via the callback.
