### ISSUE TITLE
Is possible to load image from drawable to ImageView without delay?

### ISSUE THREAD

**Issue by coulCod** [square/picasso#1470]
Hello. This is not an error, this is just question. Some times in my project happened OutOfMemoryError because of images in drawable. I try to fix this issue by using Picasso like this

> Picasso.with(getContext())
>                     .load(R.drawable.image_drawable)
>                     .into(imageView);

But now when I set R.drawable.image_drawable to imageView I faced with delay in 1 second. So, my question is. Is possible to set image from drawable dirrectory to imageView without delay?

**Comment by JakeWharton** [comment]
No. All image loading happens asynchronously so that creating the Bitmap and performing any resizes happens on a background thread instead of the main thread. If you are getting OOMs when you load it normally, that means your image is way too large for that device and you should consider embedding multiple sizes and choosing the most appropriate size for the device to reduce the amount of memory that's required to load it.
