### ISSUE TITLE
Progressive image loading / thumbnail generation

### ISSUE THREAD

**Issue by vipulyaara** [square/picasso#1544]
I am trying to imitate progressive image loading using Picasso (Assuming it doesn't have progressing image loading capability in built). The best way I can think of is generating a thumbnail and using its blurred version before original image is loaded. Is there a method in Picasso to generate thumbnails as my API doesn't have thumbnails for all the images.

Fresco has image sampling and progressive image loading support. Glide can generate thumbnails using ".thumbnail(0.1)". Any one of these functionalities with Picasso would be a big help.

**Comment by JakeWharton** [comment]
How large are the images? This seems like a waste of CPU time since you
already have to download the entire image which we stream to the bitmap
decoder so why not just decode the whole thing right away? Rendering
thumbnails from full-size images using Picasso will add anywhere from 300ms
to 500ms or more to the time it would take to just load the full image.

**Comment by vipulyaara** [comment]
Yes but
1. Is there any way Picasso can actually support progressive image loading in near future like Fresco?
2. I think it's fine to add 300ms if the user does not have to see black screen (placeholder) and rather can see actual colors in blurred image. A few examples I can think of are Instagram, Medium, Facebook cover pics etc. Now I am sure they use progressive image loading and not thumbnail generation but I have seen a few examples on Internet suggesting this method and articles stating Medium uses thumbnails. There are examples of using this method with Picasso to imitate PIL. That leads me to trust the solution.
I am in India and connections here can take noticeable time to load a standard 720x1080 image.

Can you please propose a better solution as you are definitely the right person to discuss this, as many developers would want to have progressive image loading with Picasso.

**Comment by JakeWharton** [comment]
> Is there any way Picasso can actually support progressive image loading in near future like Fresco?

If you're referring to the progressive JPEG format then no. Picasso uses Android and Bitmaps to decode images and therefore only supports what Android and Bitmap supports.

> I think it's fine to add 300ms if the user does not have to see black screen (placeholder) and rather can see actual colors in blurred image

But you already downloaded the full image. Why decode just a small part of it instead of spending a few more ms to get the whole thing?

> A few examples I can think of are Instagram, Medium, Facebook cover pics etc.

These are sent as part of the initial data payload, not downloaded separately as images.

> I am in India and connections here can take noticeable time to load a standard 720x1080 image.

The connection speed dwarfs the decoding speed by several orders of magnitude. Since you have to download the entire image to display even a thumbnail, it would be faster to just do the full decode immediately. If you want thumbnails you'll need to programmatically generate them on your server so that the download size is reduced. There's little point displaying thumbnails when you have to download the full image to generate them.

**Comment by vipulyaara** [comment]
I understand your point. I was looking for some magic solution where I do not have to download the full image to show a thumbnail. I read further about Glide's .thumbnail(0.1f) method and got to know there is no magic. The proposed method is again same as downloading full image and decoding a part of it, which is not what I want.
I guess I will have to generate thumbnails on my server. Thank you so much for your time.
