### ISSUE TITLE
Picasso to use landscape drawable variation

### ISSUE THREAD

**Issue by defaultbr** [square/picasso#1606]
i have the following scenario:

`R.drawable.my_drawable_logo (xxhdpi)`

and `R.drawable.my_drawable_logo (land-xxhdpi)`

`Picasso.with(mContext).load(R.drawable.my_drawable_logo).into(logo_holder);
`
Picasso keep using the xxhdpi and not the land variation on screen rotation

**Comment by JakeWharton** [comment]
The drawable will be cached by its ID and not reloaded until it's purged from the cache.

Since you're not using any of Picasso's features you're much better off setting/loading the drawable using the normal mechanisms. If you really want to use Picasso you'd have to either tell it to skip the memory cache or clear the cache on configuration change. Both of those options seem worse than just loading it yourself, though.

**Comment by NightlyNexus** [comment]
Or, you could do `load(R.drawable.my_drawable_logo).memoryPolicy(MemoryPolicy.NO_STORE)` if you want to use Picasso and skip the disk cache. (typically useful so you don't have to remember to `cancelRequest` if you are reusing a target.)

**Comment by JakeWharton** [comment]
Yep. That's a good one, too.

**Comment by defaultbr** [comment]
Hey guys, NO_STORE helped a lot, now its far better memory friendly, still leaking a little when i leave the activity, but its not overloaded, when i open again, the memory allocated increase a little but it return to a acceptable state, i thinks there isnt much more to do
