### ISSUE TITLE
placeholder(colorResId) works but load(colorResId) doesn't

### ISSUE THREAD

**Issue by yukuku** [square/picasso#1654]
e.g. `load(android.R.color.black)` does not load a ColorDrawable to the ImageView, but `placeholder(android.R.color.black)` correctly loads the black color drawable to the ImageView. 

I think this is inconsistent and should be fixed.

Use case:

```
val avatar = getAvatarUrlFromSomewhere()

if (TextUtils.isEmpty(avatar)) {
    picasso().load(android.R.color.black).into(imgView) // this does not work
} else {
    picasso().load(avatar).placeholder(android.R.color.black).into(imgView) 
}
```

**Comment by JakeWharton** [comment]
These methods are annotated with `@DrawableRes` on `master`. Any accidental support of color resources is simply a side-effect of the underlying Android APIs we use. If you want to load a color I suggest using a ColorDrawable or shape resource instead. We don't have plans to support loading colors since they don't really require any feature of Picasso.
