### ISSUE TITLE
picasso don't work first time.

### ISSUE THREAD

**Issue by yangbiyao** [square/picasso#1667]
final Target target = new Target() {
                    @Override
                    public void onBitmapLoaded(final Bitmap bitmap, Picasso.LoadedFrom loadedFrom) {
              
                        Log.e("DTQ", "Picasso  onBitmapLoaded:" + String.valueOf(i));
                                iv.setImageBitmap(bitmap);
            
                                markerList.add(othermarker);
             
                        });
                       //othermovetouxiang(PositionUtil.gps84_To_Gcj02(gps.getWgLat(), gps.getWgLon()), i);
                    }

                    @Override
                    public void onBitmapFailed(Drawable drawable) {

                    }

                    @Override
                    public void onPrepareLoad(Drawable drawable) {
//                        Log.e("DTQ", "Picasso onPrepareLoad");
                        Log.e("DTQ", "Picasso onPrepareLoad:" + String.valueOf(i));
                    }
                };

**Comment by yangbiyao** [comment]
I add code "iv.setTag(target)",still not work

**Comment by yangbiyao** [comment]
hope solution.

**Comment by AlexBlokh** [comment]
check network permission in manifest

**Comment by yangbiyao** [comment]
it can load image when i call the method twice

**Comment by AlexBlokh** [comment]
Can you provide a minimal code snippet to reproduce?

**Comment by liyzay** [comment]
The reason is the "Target" has been garbage collected.
Picasso use weak reference to hold "Target" in [Action](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/Action.java#L53),so gc may collected at any time,when the "Target" got garbage collected,the [CleanupThread](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/Picasso.java#610) will cancel the image load request.
You should use a strong reference to hold it.[See stackoverflow](https://stackoverflow.com/questions/33518703/picasso-first-run-not-call-onbitmaploaded-in-for-loop/33520908#33520908)
