### ISSUE TITLE
Image not loading ==> Dispatcher  batched [R3]+760ms for error, Main errored [R3]+1034ms

### ISSUE THREAD

**Issue by boyfox** [square/picasso#1670]
Hi all!
I have a following problem with loading image with Picasso:

![screen shot 2017-09-08 at 12 11 13 pm](https://user-images.githubusercontent.com/3168694/30200108-f7d50ed6-948e-11e7-810c-6d1eab7e321c.png)

this is image url: [normal image](http://booking.fussball-treff.com/media/2NZnPlbi4YBPheeYgnD0_1503924874_vmXTfLYe6xmRnri7WRz4.jpg)

this is large size of image: [large image](http://booking.fussball-treff.com/media/2NZnPlbi4YBPheeYgnD0_1503924874_vmXTfLYe6xmRnri7WRz4.jpg~large)

this is my code in adapter:

```
String firstImgURL = getFirstImgUrl(itemJS);
if (firstImgURL != null && !firstImgURL.isEmpty()) {
    Picasso picasso = new Picasso.Builder(mFrag.getContext()).loggingEnabled(true).build();
    picasso.load(firstImgURL)
            .noPlaceholder()
            .error(R.drawable.ic_no_place_image).into(holder.placeIV);
} else {
    Picasso.with(mFrag.getContext()).load(R.drawable.ic_no_place_image).into(holder.placeIV);
}
```

I don't understand by log what is problem, please help me

**Comment by cotfas** [comment]
I had the same issue.

Use the 3.0.0-Snapshot version

**Comment by JakeWharton** [comment]
Aside from the fact you're creating a new `Picasso` instance each time (don't do that), there's not enough information here to make this report actionable. At the very least we need a stacktrace that you can get by adding an exception handler to the `Picasso` instance. There's also no version information for Picasso or Android.

**Comment by boyfox** [comment]
Hi @JakeWharton thank you for great library for Square Inc, but why you close this bug if it is not fixed?

Here information which you asked:

Just single instance in App and exception handler:

![screen shot 2017-09-09 at 10 48 00 am](https://user-images.githubusercontent.com/3168694/30237576-886e8a34-954e-11e7-8bfd-32fd883a388f.png)

This is exception:

![screen shot 2017-09-09 at 10 56 49 am](https://user-images.githubusercontent.com/3168694/30237594-eee2ec60-954e-11e7-86a3-8466aef4a0cc.png)

This is using in adapter:

![screen shot 2017-09-09 at 10 59 42 am](https://user-images.githubusercontent.com/3168694/30237597-fe50d7f2-954e-11e7-80e6-8528355202c8.png)

here sdk and dependency informations:

![screen shot 2017-09-09 at 10 57 49 am](https://user-images.githubusercontent.com/3168694/30237606-11a6396e-954f-11e7-93c1-9de7e9e3eec2.png)
![screen shot 2017-09-09 at 10 58 10 am](https://user-images.githubusercontent.com/3168694/30237608-11abc974-954f-11e7-815d-4543e04a36b9.png)
![screen shot 2017-09-09 at 10 58 19 am](https://user-images.githubusercontent.com/3168694/30237607-11ab8ab8-954f-11e7-861f-f8679438868a.png)

Device: Nexus 5

**Comment by JakeWharton** [comment]
I closed it because there was not enough information and it was unclear whether you would ever respond.

The problem here is that your server is returning a 301 redirect and the HTTP client you are using (I'm guessing the built-in one) doesn't support handling redirects automatically.

The easiest way to fix this is to drop OkHttp into your app. Except, unfortunately, there hasn't been a Picasso release in a while so it will only automatically detect OkHttp 2.x. If you want to use OkHttp 3.x you can use https://github.com/JakeWharton/picasso2-okhttp3-downloader. The next release of Picasso will use OkHttp 3.x by default, so this will not be a problem.

Alternatively, if you don't want to use OkHttp, you can subclass `Downloader` and use `HttpURLConnection` like the built-in one but add code to handle redirects yourself. Picasso doesn't do this by default because it should be the HTTP's client's responsibility to follow redirects.

**Comment by boyfox** [comment]
Thank you for clearly explaining @JakeWharton, I will use picasso 2-okhttp3-downloader or Picasso next release snapshot version.
