### ISSUE TITLE
Queue or all at once?

### ISSUE THREAD

**Issue by smhk** [square/picasso#1672]
I have a remarkably basic question about PIcasso, which is critical, and to which I can't find the answer anywhere !

Quite simply, if I stack up ten calls to Picasso - does it queue them, or, try for all at once?

(I asked as much here ... https://stackoverflow.com/q/46131941/294884 for example.)

I love Picasso and have been a huge supporter over the years, I must admit I don't know this basic/critical info!

**Comment by JakeWharton** [comment]
It queues. By default, the number of concurrent downloads varies between 2 and 5 depending on the quality of your connection. If you change the `Executor` (which can be done on `Picasso.Builder`) this auto-scaling does not happen, but you can then control the number of threads which you want running at once.

Calls to `get()` which are not asynchronous do not queue and you can make as many as you want at a time (because it's your thread that's being blocked).

**Comment by smhk** [comment]
THANKS for that
