### ISSUE TITLE
Error: cannot find symbol method get() in 3.0.0-SNAPSHOT version

### ISSUE THREAD

**Issue by CoolMind** [square/picasso#1777]
Picasso.get()
                .load(url)
                .into(imageView, callback);

Yesterday compiled well. Today is an error. What do you do with your library? Don't advise to update to this version in other issues!

**Comment by motcwang** [comment]
So am I

**Comment by jrodbx** [comment]
We're actively developing the next major release.  As we don't currently timestamp our snapshots, expect more breaking changes...

Where are we advising to update to this snapshot?  Let us know so we can correct.

**Comment by CoolMind** [comment]
@jrodbx
https://github.com/square/picasso/issues/1684
https://github.com/square/picasso/issues/1514
I started plugging it after https://github.com/square/picasso/issues/364, though it wasn't advised directly. At that moment that version of the snapsot was stable and satisfied the needs.

**Comment by jrodbx** [comment]
In both cases, it was suggested to try but not necessarily depend on the snapshot -- a local or internal copy of the lib is probably the best course of action, as the API is likely to change as we push to a 3.0

**Comment by NightlyNexus** [comment]
yeah, you want deterministic builds.
consider downloading an aar from the snapshots repository to pin to one release.

**Comment by CoolMind** [comment]
Sad that I didn't know builds would often change. I have no a library of February, 20-27 dates, so have to return to 2.5.2.
Even if it was offered to try, this recommendation is now incorrect, as the library is unstable.

**Comment by NickToony** [comment]
After some digging, it seems the Picasso.get() was moved into a separate module/provider. As a super quick workaround, you can:

1. Edit your dependencies to import the new provider
```
compile 'com.squareup.picasso:picasso:3.0.0-SNAPSHOT'
compile 'com.squareup.picasso:picasso-provider:3.0.0-SNAPSHOT'
```
2. Replacing `Picasso.get()` with `PicassoProvider.get()`
3. Be aware that the API may change again at any time

I couldn't find an archived snapshot, so resorting to still using the latest snapshot (though will now download a copy). I'd really hope this library coul release a new version, or a versioned snapshot - 3.0.0 has resolved a lot of bugs for me, and been super stable otherwise! Thanks.
