### ISSUE TITLE
Not working with Oreo notifications... how to send channel ID to notification manager

### ISSUE THREAD

**Issue by Hanzala717** [square/picasso#1874]
Not working with Oreo notifications... how we can send channel ID to notification manager while that's from inside your classess.
that's why it's not working

**Comment by JakeWharton** [comment]
You supply the `Notification` object so that is your responsibility. The sample shows this: https://github.com/square/picasso/blob/b8945259fb40efd304fd7f4176e6d2a9cef92ca7/picasso-sample/src/main/java/com/example/picasso/PicassoSampleAdapter.java#L38-L64

If you think you have a bug, please provide a failing test case or executable sample that demonstrates the problem in isolation so that we can debug and correct it.

**Comment by Hanzala717** [comment]
Thank you for correction
