### ISSUE TITLE
RequestCreator picasso property visibility

### ISSUE THREAD

**Issue by SamYStudiO** [square/picasso#2016]
Shouldn't `picasso` property from `RequestCreator` be public instead of private?
I guess this is not sensitive at all since `RequestCreator` is created from it and if you want to make some kotlin extensions with `RequestCreator` you may want to get `Picasso` instance that load this `RequestCreator`.

**Comment by JakeWharton** [comment]
No one has provided a reason for it to be public. Ideally it wouldn't have a reference at all.

**Comment by SamYStudiO** [comment]
I'm trying to make some RequestCreator kotlin extensions to return reactive stream, something like 

`fun RequestCreator.observeInto(imageView: ImageView) : Completable = RxPicasso.requestInto(this, imageView)`

I'd like to cancel request if stream is disposed before completing and i have no reference to `Picasso` to make that cancel happend, do you think the right way to go is to pass that Picasso instance? something like :

`fun RequestCreator.observeInto(picasso: Picasso, imageView: ImageView) : Completable = RxPicasso.requestInto(picasso, this, imageView)`

I wish i could get rid of that `Picasso` argument though.

Thx

**Comment by JakeWharton** [comment]
I would like to decouple the request entirely from Picasso and make it a value type so we have clean separation of the request and the thing which executes the request. This also allows us to make it immutable where any transformations have to return a new instance. That would solve this case since you would just add an extension to `Picasso` which accepted a request.

**Comment by SamYStudiO** [comment]
ok thanks for the heads up
