### ISSUE TITLE
Image not showing on android for work

### ISSUE THREAD

**Issue by LGstudio** [square/picasso#2100]
I have 2 same tablets. One is having as android for work profile as the application I am currently developing is used for corporate work.
On the regular tablet this code of showing an image from the internal storage works:
`File img = new File(actualMissionLocation.getAbsolutePath() + "/" + location.getName() + ".jpg");        Picasso.get().load(img).into(imageView);`
This same code does not work on the device with the AFW. It is showing a black screen. The .jpg image was saved by my application and it is there in the file system. I have tried with Uri in the format of "file://..." but also did not work on AFW.
What seems to be the problem here? Thanks for your help in advance.

**Comment by saqibmirza2007** [comment]
@LGstudio  have you find any solution on this?

**Comment by JakeWharton** [comment]
Picasso delegates to the Android framework to load bitmaps from the filesystem. If the image cannot be read by Picasso, it cannot be read by any code. This is perhaps due to the restriction imposed on Android for Work profiles, but it's impossible to be sure without more info. Going to close since there appears to be no action Picasso can take here.
