### ISSUE TITLE
Update Javadoc

### ISSUE THREAD

**Issue by dave-kennedy** [square/picasso#2115]
As far as I can tell, the only documentation that exists for this library is the Javadoc. The README points to [the website](http://square.github.io/picasso/), which contains a few useful examples, but not much. The website points to an [outdated version of the Javadoc](https://square.github.io/picasso/2.x/picasso/). How do we update that?

**Comment by JakeWharton** [comment]
I will update the javadoc later. It requires using osstrich which we mistakenly did not script.

That being said, what's on `master` and what's on the website are not expected to match because `master` is where code is developed. If you need to check the README for something it's best to use a tag which corresponds to the version you are using.

**Comment by JakeWharton** [comment]
Updated.
