### ISSUE TITLE
IllegalArgumentException on empty path

### ISSUE THREAD

**Issue by TorkelV** [square/picasso#2186]
If i do:
`Picasso.get().load(imageUrl).placeholder(placeholder).error(placeholder).into(this)`

I would expect any error to load the placeholder. And that's what happens in all cases, with one exception. If `imageUrl.trim().length == 0` it throws `IllegalArgumentException`.

Is that exception really necessary? Why?

For reference: 
```  
public RequestCreator load(@Nullable String path) {
    if (path == null) {
      return new RequestCreator(this, null, 0);
    }
    if (path.trim().length() == 0) {
      throw new IllegalArgumentException("Path must not be empty.");
    }
    return load(Uri.parse(path));
  }
```

**Comment by JakeWharton** [comment]
Because an empty string is neither absence nor a valid Uri. We do not propagate malformed data but rather reject it at the library boundary. If your data can contain malformed data such as an empty or blank string, you should normalize it to `null` before it enters the library.

See #426, #899, #1922, and others for previous discussion.
