### ISSUE TITLE
picasso image rotation issue in android 10 using Uri of image

### ISSUE THREAD

**Issue by MohammedHassouna** [square/picasso#2205]
Picasso has an image rotation issue when showing it in android 10 using Uri of image

    Uri uri = "content://media/external/images/media/12155";
    Picasso.get().load(uri).into(imageView);

I'm used the last version 2.8

![Roation issue](https://i.ibb.co/8s5d5XC/Screenshot-2021-05-03-09-05-02-595-au-tilecleaners-app.jpg)

this is the original image

![original image](https://i.ibb.co/QJjHBY1/IMG-20210503-090344.jpg)

this issue not found if android API 28 for example the issue happened with greater than or equals to android 29

this is the image for the test
https://drive.google.com/file/d/1_VFpwrp3o6ZVUe7YmHcIDtF1PYI19NFz/view?usp=sharing
remove this flag from manifests requestLegacyExternalStorage=true

**Comment by usuiat** [comment]
I have a same issue.
The cause is the value of orientation.
MediaStoreRequestHandler.java returns integers like 90, 180 and passes them to BitmapHunter.java, while BitmapHunter.java expects to be passed constants like ExifInterface.ORIENTATION_ROTATE_90. As a result, the orientation value obtained by MediaStoreRequestHandler.java is ignored.
