### ISSUE TITLE
Picasso 2.5 cache every http calls

### ISSUE THREAD

**Issue by wing650473** [square/picasso#2215]
I was using Picasso 2.5 lib to load some images from my server in one of the fragments, and other fragments I used SAXParserFactory to get some XML files.  But I found that when the user get into the fragment with images (Picasso initialised) then when the user go to any other fragments on getting XML files, all the XML files  will  be cached under "picasso-cache" even I specified "NO_CACHE" on image's fragment.  It only happens if the user visited the image's fragment once. (ie Picasso initialised)

 It seems very strange to me, so does Picasso 2.5 override any http calls?

Please help, coz seems it didn't happen on Picasso 2.8, at least didn't cache the xml files.

**Comment by JakeWharton** [comment]
> all the XML files will be cached under "picasso-cache" even I specified "NO_CACHE" on image's fragment.

The files under `picasso-cache/` are from OkHttp's filesystem-based HTTP cache and are controlled the headers on the response from your server. Picasso does not interact with this cache directly nor does it have any control over it. We merely create a directory and tell OkHttp to use it. This cache holds original responses from the HTTP layer.

The `NO_CACHE` directive controls the memory cache, which otherwise stores the final transformed objects. By specifying that you do not want the result cached each request will ask the HTTP client for the original and transform it. OkHttp may serve that response from the cache, or it may make a network call. Picasso doesn't know and doesn't care.

Hope that clarifies the behavior.
