### ISSUE TITLE
No Exception

### ISSUE THREAD

**Issue by Asem-Abdelhady** [square/picasso#2216]
The library should throw an exception or an error when the URL is not provided for an image. Maybe it would be better for the user to provide such implementation to free him from debugging

**Comment by JakeWharton** [comment]
Decoding failures are sent to the [`Picasso.Listener`](https://square.github.io/picasso/2.x/picasso/com/squareup/picasso/Picasso.Listener.html) which you can attach to your `Picasso.Builder`. We will not be throwing exceptions to call sites for actual failures since the URL still may be an image but simply fail to decode. Or it may not be an image. We cannot know the difference.

**Comment by Asem-Abdelhady** [comment]
Got you. But is it possible to throw one if it was an actual image but
failed to decode or we still cannot know if failed to decode.

**Comment by JakeWharton** [comment]
It is impossible to make a distinction between an image which failed to decide and non-image data with 100% accuracy. Moreover, we delegate to the Android platform APIs for image decoding and it does not expose this information.
