### ISSUE TITLE
Declarative Cache Control API

### ISSUE THREAD

**Issue by JakeWharton** [square/picasso#438]
I've been sitting on this for a while as a future feature but hadn't documented it.

The API would allow specifying a cache interaction policy both "downward" on the load and "upward" back through the processing. Through this you can facilitate complex cache interactions for both valid and seemingly-questionable use cases.

Random subset of interactions from other issues:
- Skip memory cache "downward" only.
- Skip memory cache "upward" only.
- Load from local cache (memory or disk) only.
- Force re-load from network.

I'm not going to do a full-on API strawman, but I know we'll probably want some `EnumSet` action with

``` java
public enum BitmapSource { MEMORY, DISK, NETWORK }
public enum BitmapSink { MEMORY, DISK }
```

This API will trump the existing weak `skipCache()` method on `RequestCreator`.

**Comment by jvcjunior** [comment]
Sorry if this question is silly.
I am loading images from disk. When I remove the file from gallery the image still loads. What should I do to invalidate this image or clean this specific image from cache? I don't understand how to do it using MemoryPolicy or NetworkPolicy.

**Comment by dnkoutso** [comment]
Read MemoryPolicy and NetworkPolicy JavaDoc.

`picasso.load(url).memoryPolicy(NO_CACHE).networkPolicy(NO_CACHE)` to force the request to reload from the network.

There is also `clearKeyUri` in `Cache` you can use to evict the image from the memory cache.

**Comment by Karlooie** [comment]
Hello,
I'm facing a problem with  network policy. 

my code to reload an image from network is:

                Picasso.with(MainActivity.this).load(url)
                        .networkPolicy(NetworkPolicy.NO_CACHE)
                        .memoryPolicy(MemoryPolicy.NO_CACHE)
                        .into(mPicassoTg);

note: mPicassoTg is a field of my main activity, so I hope it's not garbage collected.

behavior:
mPicassoTg.onBitmapLoaded is NOT CALLED. (nor is onBitmapFailed)
mPicassoTg.onPrepareLoad is called

Everything works fine if I remove networkPolicy setter, 
It works also on a new image, that is not in the cache (network is working and url is correct).

                Picasso.with(MainActivity.this).load(url)
                        .memoryPolicy(MemoryPolicy.NO_CACHE)
                        .into(mPicassoTg);



Am I missing something?
need more details?

Thank you for the great Picasso and all the support,
Carlo

**Comment by oliverhausler** [comment]
I want to use disk cache, but not cache any images in memory (in order to keep memory consumption low), but as it looks

.memoryPolicy(MemoryPolicy.NO_STORE)

implicitly applies NetworkPolicy.NO_STORE as well. Is this a bug or can I get around this? Does my approach of reducing memory consumption make sense at all?

**Comment by JakeWharton** [comment]
Just set a Cache instance which does nothing. Then you don't have to worry
about including those options on every call.

**Comment by oliverhausler** [comment]
I'm not worried about calling this on every call, I want to use disk cache, but not memory cache. Is that possible and does that make sense at all? (I am handling many large images, which are not accessed often, so I want to cache them on disk, but not in memory. GC is slow sometimes and my app crashes due to high memory consumption, even though I have removed all my references already. So I wanted to have the least load on memory possible.)

**Comment by JakeWharton** [comment]
Picasso only has a memory cache so making it no-op won't affect the disk
caching (which lives in the HTTP client).

I can look into the cache API behavior later.

**Comment by mrafieej** [comment]
@JakeWharton 
I am having memory issues also. could you please elaborate on what the right way to set a Cache instance is? Thanks!

**Comment by mrafieej** [comment]
Also invalidate is not working for me some reason. I am calling it like this (called from an activity):
Picasso.with(this).invalidate(image_url);
I want to load the new image when the user uploads a new one, but it is not working for some reason... I would appreciate any comments on that as well.

**Comment by rjcristy** [comment]
I have the same problem with @mrafieej . When I use invalidate after the basic method of loading an image, somewhere during the application, the images don't show anything (since there is no error image, which is fine to me),

I am trying any codes posted here but no luck. A detail of the problem is this: when the user changes the image from another device or platform (Web browser, or in an IOS device), it doesn't update the image in the android app. Can you help me? Thanks!

**Comment by danielbeutel** [comment]
How would we use this to cache images only for the lifetime of a component (Fragment, ViewGroup, ...)?
Use case: We have a fragment with a grid of images which should be cached for the lifetime of the fragment. When the user navigates away from and back to the fragment we want the images to reload.

**Comment by omid-nazifi** [comment]
Hi, I wanna cache images in memory by Picasso but I have a problem for reloading. Is it possible changing an image when its resource has changed in server. In other words, when network is off, used from cached image in memory and when network is On check the URL, If resource has changed then reload image. if not use a previous image.
Please let me know it is possible or not? And How can I do it?

Thanks

**Comment by parthanjaria** [comment]
I am also facing similar problem. I am using 2.5.2 version. 

I have an image(profile_picture) at a url. Now i want that to be cached. But when I re-upload/change the image on the server with same link, i want picasso to update that image. 

I tried using invalidate(url), memoryPolicy(NO_CACHE), networkPolicy(NO_CACHE) but nothing seems to work. need urgent solution
