### ISSUE TITLE
Image download callback

### ISSUE THREAD

**Issue by himanshurb** [square/picasso#59]
Hi,

Can I register a callback method on each into request so that I can do custom stuff after the image has downloaded ? 

For eg: hide the progress bar, show custom notifications etc. 

It would be really helpful.

**Comment by lgmcben** [comment]
Hi.

I'm asking in this thread because I think It's related. And also to avoid creating a similar/duplicate thread. This should benefit those who're using the new RecyclerView as well.

I'm trying to make PIcasso load image from "main_url". And if it fails, try "failover_url" instead.

Here's the code:

       @Override
       public void onBindViewHolder(final ViewHolder holder, int position) {
            Picasso.with(mContext)
                    .load("main_url")
                    .placeholder(R.drawable.placeholder)
                    .error(R.drawable.error)
                    .fit()
                    .tag(mContext)
                    .into(holder.image, new Callback() {
                        @Override
                        public void onSuccess() {

                        }

                        @Override
                        public void onError() {
                            Picasso.with(mContext)
                                    .load("failover_url")
                                    .placeholder(R.drawable.placeholder)
                                    .error(R.drawable.error)
                                    .fit()
                                    .tag(mContext)
                                    .into(holder.image);
                        }
                    });
    }


Questions :
1) According to the doc : 
> 
public void into(android.widget.ImageView target,
                 Callback callback)
Asynchronously fulfills the request into the specified ImageView and invokes the target Callback if it's not null.
Note: The Callback param is a strong reference and will prevent your Activity or Fragment from being garbage collected. If you use this method, it is strongly recommended you invoke an adjacent Picasso.cancelRequest(android.widget.ImageView) call to prevent temporary leaking.

Since I'm loading each image in onBindViewHolder() in RecyclerView.Adapter subclass, I have no idea where should I invoke Picasso.cancelRequest() ?

2) Is this a proper approach to implement failover url with Picasso?

Thank you. =)

**Comment by JakeWharton** [comment]
If you want fail over you should implement your own RequestHandler which
tries multiple URLs.

**Comment by lgmcben** [comment]
Thanks for a very fast response.

RequestHandler works. But the above code also works fine as well. 

I assume there maybe some drawbacks when using the Callback to initiate another image downloading?

**Comment by JakeWharton** [comment]
The callback-based approach will be slower since it requires taking
multiple round trips through Picasso's threading model. Other than that
there's not much downside as far as I can think of (this early in the
morning).

**Comment by GPack1** [comment]
@dnkoutso At what point of an adapter we have to cancel the request to prevent leaking, when adapter is destroyed?

> Yes it is highly recommended canceling downloads with a callback otherwise until the download occurs a strong reference is kept and it temporarily prevents GC.
