### ISSUE TITLE
Unable to set RequestHandler.Result#orientation from outside of Picasso package

### ISSUE THREAD

**Issue by jacobtabak** [square/picasso#653]
I am trying to implement a custom RequestHandler that handles EXIF orientation but there is currently no way to specify the orientation from outside of the Picasso package.  [Here is a snippet from RequestHandler.java](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/RequestHandler.java#L54-L62):

    public Result(Bitmap bitmap, Picasso.LoadedFrom loadedFrom) {
      this(bitmap, loadedFrom, 0);
    }

    Result(Bitmap bitmap, Picasso.LoadedFrom loadedFrom, int exifOrientation) {
      this.bitmap = bitmap;
      this.loadedFrom = loadedFrom;
      this.exifOrientation = exifOrientation;
    }

I understand a workaround would be to perform the transformation in my RequestHandler, but would prefer to avoid duplicated code.

**Comment by jacobtabak** [comment]
I'll close this because it's ancient.

**Comment by guillaume-tgl** [comment]
Is it possible to reopen this issue because it's still not possible to specify the exif orientation when returning a `Result` from a custom `RequestHandler`. It's even more needed now than when this issue was first opened because it's now possible to construct a `Result` with an `InputStream` instead of a `Bitmap`.
