### ISSUE TITLE
Implement a Bitmap pool for Picasso

### ISSUE THREAD

**Issue by lucasr** [square/picasso#672]
I haven't looked very deep into this yet but it seems Glide does a good job reusing Bitmaps and reducing GC pauses on image-heavy UIs. The new APIs in #665 will definitely help with reducing GC but using a Bitmap pool seems like a good idea anyway.

The Bitmap pool implementation could actually be a standalone library. I wonder if @sjudd (Glide's creator) would be interested in collaborating? Or maybe Picasso should have its own Bitmap pool implementation. Dunno.

Just filing this ticket to get some discussion going. Thoughts?

**Comment by eboudrant** [comment]
May be Ymagine (https://github.com/yahoo/ygloo-ymagine) could help for bitmap pooling, it is an alternative to the android.graphics.BitmapFactory and is very performant with complex rescaling (different size of images in the pool).

https://github.com/yahoo/ygloo-ymagine/blob/master/src/com/yahoo/mobile/client/android/ymagine/BitmapFactory.java

**Comment by JakeWharton** [comment]
Yep. At the very least, it would be cool to have the option to use it.

**Comment by mullender** [comment]
Sharing some data about the possible improvement in performance this feature good provide.

I did a quick and dirty experiment with bitmap pooling in Picasso. 
Using the sample app on an API19 emulator, scrolling all the way down, then all the way up.
the garbage collection times without bitmap pooling add to 1044ms
with bitmap pooling, the GC takes 462ms. 
About a 55% percent reduction in GC pauses. 

Keep in mind this data is from a quick experiment.

**Comment by mullender** [comment]
I just posted a PR that implements bitmap pooling. 
The API is very explicit:
- you must enable bitmap pooling:
```
        Picasso.setSingletonInstance(new Picasso.Builder(this).bitmapPool(new BitmapPoolImpl()).build());
```
- your view code must release the reference explicitly:
```
    Picasso.with(context).recycle(view);
```

For the sample application it reduces the time spent in GC and the frequency of GC by half.

**Comment by mullender** [comment]
@JakeWharton @lucasr Have you had a chance to look at this? And could you provide some feedback

**Comment by Macarse** [comment]
Any update on this?

**Comment by mullender** [comment]
Can you please give an indication of when someone will take a look?

**Comment by mullender** [comment]
ping

**Comment by mullender** [comment]
https://github.com/square/picasso/pull/1150

**Comment by sxsx0723** [comment]
any update on this？

**Comment by Miha-x64** [comment]
> We definitely cannot force use of a custom ImageView.

Yes, but you can force use of a custom Drawable!
There's PicassoDrawable already. I can imagine the following scenario:
* exposing a Bitmap (e.g. via Target) makes it unrecycleable; new Target2 interface accepts a Drawable
* all Picasso Drawables are managed and tracked by reuse facility
* a Bitmap can be stolen from a PicassoDrawable if it `!isVisible()` both for reuse and for memory trim
* if our Drawable becomes visible again, it requests Bitmap from Picasso and draws placeholder while Bitmap gets read and decoded.

P. S. Many people say Glide is good at image reuse. I hate it for being binary incompatible and bloated but currently it is very popular particularly for careful memory usage. While this issue is lying down here since 2014, users are getting away :( they are forced to use crappy Glide to avoid OOMs.

**Comment by JakeWharton** [comment]
No plans to add this. You can't even do it with ImageDecoder, anyway.

**Comment by Miha-x64** [comment]
Thanks, this explains everything.
For further diggers: [ImageDecoder#decodeBitmapImpl](https://github.com/aosp-mirror/platform_frameworks_base/blob/d172a0cff8b7b3a4332d5992a87c5e3ab1784174/graphics/java/android/graphics/ImageDecoder.java#L1869).
