### ISSUE TITLE
Picasso Memory

### ISSUE THREAD

**Issue by LinkOut** [square/picasso#871]
Lets make an example: We have 2 Activity A and B, both of em are using Picasso library to show images.

When i switch from A to B (Intent) since B got ImageViews, the memory required is higher.
But when i get back to A seems that GC does not clear the memory...

How to handle this?

Thanks

**Comment by JakeWharton** [comment]
There is not enough information in this issue to be actionable. We have no idea how you are using Picasso, what other factors are contributing to the memory usage patterns, and how you are measuring memory use.

If you think this is truly a bug, please provide a barebones sample application which concretely demonstrates the problem. Please also include how you are measuring and what the expected behavior is.
