### ISSUE TITLE
PlaceHolder and Error images resize

### ISSUE THREAD

**Issue by ezefire** [square/picasso#904]
Does Picasso resize the placeHolder or the image to put when the load fails before putting it into the target with de indicated sizes? Because I'm getting an OutOfMemoryError in old devices when setting that drawable. I thought two solutions to that problem. The first of them is to resize manually the drawable before calling Picasso and the other is to add multiple sizes of the same drawable (this option is discarded).  But I think this feature should be inside Picasso.

**Comment by JakeWharton** [comment]
No. Both should be sized appropriately. We rely on the GPU for any scaling.

**Comment by ezefire** [comment]
OK! Thanks for your response.

**Comment by JakeWharton** [comment]
We absolutely don't do this for placeholders because we need to set them synchornously. Resizing is an async operation and when a listview is scrolled (and views are reused) we need to put something in the view when its recycled. You don't want your placeholders popping in after the view is already on screen.

As to error images, there's two reasons: they should never be seen in an ideal world (not true in practice, of course) and we simply don't want to make the image loading pipeline complex by doing multiple async resizing operations.
