### ISSUE TITLE
Support for removing all the images from cache 

### ISSUE THREAD

**Issue by fahimsakri** [square/picasso#935]
Is there a way we can remove all the images from cache, i came across invalidate() method, but we need to pass the file as parameter.

**Comment by dnkoutso** [comment]
Not really but you can keep a reference to your Cache and clear it yourself. Perhaps we can add an `invalidateAll` in the API...

**Comment by JakeWharton** [comment]
Why?

**Comment by fahimsakri** [comment]
@JakeWharton because my app is taking to much memory because of images and i want to clear them everytime my app freshly opens

**Comment by JakeWharton** [comment]
Unused memory is wasted memory. How are you measuring "too much memory"?

If the app is restarted the memory cache will already be empty. Otherwise you are forcing Picasso to re-decode (and potentially re-download) images which will cause wasteful battery and CPU use.

If you really want to do this, you can create your own `LruCache` instance, passing it to Picasso, and calling `clear()` on it.
```java
Cache cache = new LruCache(...);
// Save this 'cache' object somewhere.
Picasso picasso = new Picasso.Builder(context)
    .setCache(cache)
    .build();
Picasso.setSingletonInstance(picasso);

// Later...
cache.clear();
```
