### ISSUE TITLE
Transparent images overlaid in ListView adapter

### ISSUE THREAD

**Issue by JayNewstrom** [square/picasso#936]
I have a ListView with an adapter which uses picasso to set transparent images, after scrolling (view reuse) the images appear on top of the one previously used for that row. As you can see in the screen shot, I have scrolled up and down on the top half, to show overlapping, the bottom rows haven't been reused because I didn't scroll them off screen.
![screenshot_2015-03-19-15-09-52](https://cloud.githubusercontent.com/assets/713288/6739925/3f505fe4-ce4a-11e4-8f83-07c25a013c7b.png)

**Comment by JakeWharton** [comment]
List version and show adapter code.

**Comment by JayNewstrom** [comment]
Just started happening on 2.5.1 it's very simple adapter code. Just picasso.load(url).into(imageView); I can put together a sample app if need be.

**Comment by JakeWharton** [comment]
Probably due to the switch to `TransitionDrawable` in #855. cc/ @dlew

**Comment by JakeWharton** [comment]
Are you using placeholders?

**Comment by JayNewstrom** [comment]
Not in the place that it is happening.

**Comment by dlew** [comment]
It could definitely be related. Which OS version? Maybe `TransitionDrawable` won't work so well on older platforms.

**Comment by JayNewstrom** [comment]
I've only tried it on 4.4, 5.0, 5.1 and it's happening on all of them.

**Comment by dlew** [comment]
Could you give a sample of it happening?

**Comment by JayNewstrom** [comment]
https://github.com/JayNewstrom/picassoOverlay

**Comment by dlew** [comment]
Thanks! I'll take a look soon.

**Comment by dlew** [comment]
Early results: `TransitionDrawable.setCrossFadeEnabled(true)` in `PicassoDrawable`'s constructor fixes the issue.

Not 100% sure why yet; going to keep digging in until I know for sure what's going on.

**Comment by dlew** [comment]
Aha! I see the second problem, which is larger than the first. It's that `PicassoDrawable` uses the `ImageView`'s current drawable as a placeholder. Since the `ImageView` is being recycled that means it's using a `PicassoDrawable` as the placeholder for another `PicassoDrawable` and layered drawable madness ensues.

We just need to prevent `PicassoDrawable` from using itself as a placeholder. It should not only fix this problem but there are also performance implications it causes for opaque images (since it'll be drawing previous layers behind it).

We still need to enable cross fades, otherwise both the placeholder *and* the bitmap render after the transition is completely (which would cause transparent images to fail).

@JakeWharton I'm sincerely sorry this happened, I'll setup a PR to fix both issues.
