### ISSUE TITLE
Exception: Transformation rounded returned input Bitmap but recycled it

### ISSUE THREAD

**Issue by cnordvik** [square/picasso#997]
I get this error on a rounded transformation on one of our users profile picture. Any idea on how to handle this properly? 

The images that causes all the issues is this one: 
https://graph.facebook.com/675276189284495/picture?type=large

We have hundreds of others and none of them make the transformation crash except this FB profile image. 

    E/AndroidRuntime(14239): java.lang.IllegalStateException: Transformation rounded returned input Bitmap but recycled it.
    E/AndroidRuntime(14239): 	at com.squareup.picasso.BitmapHunter$5.run(BitmapHunter.java:462)
    E/AndroidRuntime(14239): 	at android.os.Handler.handleCallback(Handler.java:739)
    E/AndroidRuntime(14239): 	at android.os.Handler.dispatchMessage(Handler.java:95)

Here is some of the code for the transformation:

    @Override
    public Bitmap transform(final Bitmap source) {
        try {
            int size = Math.min(source.getWidth(), source.getHeight());

            int x = (source.getWidth() - size) / 2;
            int y = (source.getHeight() - size) / 2;

            Bitmap squaredBitmap = Bitmap.createBitmap(source, x, y, size, size);
            if (squaredBitmap != source) {
                source.recycle();
            }

            Bitmap bitmap = Bitmap.createBitmap(size, size, source.getConfig());

            Canvas canvas = new Canvas(bitmap);

            Paint paint = new Paint();

            BitmapShader shader = new BitmapShader(squaredBitmap, BitmapShader.TileMode.CLAMP, BitmapShader.TileMode.CLAMP);
            paint.setShader(shader);
            paint.setAntiAlias(true);

            Mode mMode = Mode.DST_OVER;
            paint.setColorFilter(new PorterDuffColorFilter(Color.argb(255, 255, 255, 255), mMode));

            float r = size/2f;
            canvas.drawCircle(r, r, r, paint);

            squaredBitmap.recycle();
            return bitmap;
        }
        catch(Exception ex)
        {
            return source;
        }

    }

**Comment by f2prateek** [comment]
I'm guessing that your code goes down the `if (squaredBitmap != source) { source.recycle(); }` path and recycles the `source` bitmap. There's a quite a bit that happens after that line, and that code can throw an exception. Since you catch this exception and end up returning `source` anyway (which is already recycled), Picasso complains about it.

Remove the `catch(Exception ex)` block aand you shouldn't have this issue.

**Comment by cnordvik** [comment]
I removed that and it crashed with: 
Caused by: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
app.util.RoundedTransformationGlide.transform(RoundedTransformationGlide.java:29)

which is the same as the one who wrote this comment (he is using Glide but still seems like the same issue):
http://stackoverflow.com/questions/27394016/how-does-one-use-glide-to-download-an-image-into-a-bitmap#comment43272651_27394484

and he has a gif, same as me. So doesn't this transformation work with GIFs?

**Comment by JakeWharton** [comment]
If it does not then it's an Android bug. The cause of the original problem was identified (returning a recycled bitmap in your catch block) and the rest of the code looks good as far as the transformation goes. For further problems you'll have better luck elsewhere (such as StackOverflow) as it's not a problem with Picasso specifically.

**Comment by heitorcolangelo** [comment]
The problem is when Android performs this line in CircleTransform.java:
````java
Bitmap bitmap = Bitmap.createBitmap(size, size, source.getConfig()); 
````
If the image is a GIF, this method returns null.
Add this line berfore the first mentioned:
````java
Bitmap.Config config = source.getConfig() != null ? source.getConfig() : Bitmap.Config.ARGB_8888;
````
and then change the last parameter to config, like this:
````java
Bitmap bitmap = Bitmap.createBitmap(size, size, config);
````
The final code should be like:
````java
// For gif images
Bitmap.Config config = source.getConfig() != null ? source.getConfig() : Bitmap.Config.ARGB_8888;
Bitmap bitmap = Bitmap.createBitmap(size, size, config); 
````

Reference: comment of alxscms in this link
https://gist.github.com/julianshen/5829333

**Comment by crysxd** [comment]
A little unrelated but this discussion was the first hit in Google for my issue. Maybe it helps someone :) My app crashed with the same error, the reason was that I used 
    
    val result = Bitmap.createBitmap(
         source,
         minX,
         minY,
         maxX - minX + 1,
         maxY - minY + 1
     )
     source.recycle()

but if the dimensions of the created Bitmap where identical to source, `createBitmap` returns source which then got recycled. The documentation of `createBitmap` says `The new bitmap may be the same object as source, or a copy may have been made`. Solution: 

    if (source != result) {
        source.recycle()
    }
